version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-fitness
    environment:
      - =value
  db:
    image: postgres:14-alpine
    ports:
      - 
 


  